# Bluetooth базовые параметры
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_ZMK_BLE=y

# Службы устройства
CONFIG_BT_DIS=y
CONFIG_BT_BAS=y

# Критично для Windows 11
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Увеличить мощность передатчика
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Uncomment the following lines to enable the Corne RGB Underglow
CONFIG_LED_STRIP=n
#CONFIG_ZMK_RGB_UNDERGLOW=n
#CONFIG_WS2812_STRIP=n
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_SLEEP=y
# CONFIG_PM_DEVICE=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y

CONFIG_ZMK_KEYBOARD_NAME="RISATENO"

# Tune combos to allow proper Taipo support
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=128
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=10
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=10
    
# ZMK Studio                          
#CONFIG_ZMK_STUDIO=y
#CONFIG_ZMK_STUDIO_LOCKING=n
